### ISSUE TITLE
Adding more Commands and Updating Readme.MD

### ISSUE THREAD

**Issue by sbdh11** [DeltaCoderr/discord-bot-handler#6]
If anyone is up for adding more commands, and updating the readme file, Feel free!

**Comment by Gautam-Arora24** [comment]
Can I go ahead?

**Comment by Gautam-Arora24** [comment]
Should I need to make the Readme.md cleaner?

**Comment by sbdh11** [comment]
yeah, just explain about how the installation works and the command list.

**Comment by MaheshNat** [comment]
I'm thinking about adding a poll command, to vote yes or no for a given question.

**Comment by sbdh11** [comment]
go ahead

**Comment by sbdh11** [comment]
@Gautam-Arora24 Are you gonna do it soon or should I do it?

**Comment by Gautam-Arora24** [comment]
@DeltaCoderr  Go Ahead and solve it
